name: Build and push image to Docker repo
on:
  # Triggers on tag pushes
  push:
    tags:
      - 'v*'
# Using Project 3 repo since I already had it created
env:
  DOCKER_HUB_REPO: hameed-project3
jobs:
  build_and_push:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      # Check out repo
      - name: Check out the repo
        uses: actions/checkout@v4
      # Set up buildx
      - name: Docker Buildx
        uses: docker/setup-buildx-action@v3
      # Login to DockerHub 
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      # Metadata 
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with: 
          images: ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_HUB_REPO }} 
     
      # Build and push
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_HUB_REPO }}:Project4
            ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_HUB_REPO }}:latest

