name: Build and Push Images to Docker Repo
on:
  # triggers on push to main branch
  push:
    branches:
      - 'main'
# Using Project 3 repo since I already had it created
env:
  DOCKER_HUB_REPO: hameed-project3
jobs:
  build_and_push:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ env.DOCKER_HUB_REPO }}
          tag_with_ref: true
